package com.alximik.capoeiralyrics.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;


import com.alximik.capoeiralyrics.entities.Song;
import com.alximik.capoeiralyrics.entities.SongDao;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;



// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig songDaoConfig;
    //private final DaoConfig favouriteDaoConfig;

    private final SongDao songDao;


    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        songDaoConfig = daoConfigMap.get(SongDao.class).clone();
        songDaoConfig.initIdentityScope(type);


        songDao = new SongDao(songDaoConfig, this);


        registerDao(Song.class, songDao);


    }
    
    public void clear() {
        songDaoConfig.getIdentityScope().clear();
    }

    public SongDao getSongDao() {
        return songDao;
    }

//    public FavouriteDao getFavoriteDao() {
//        return favouriteDao;
//    }



}
